steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - createPubSubTopic
      - --region=us-central1
      - --source=.
      - --entry-point=org.example.TopicCreation
      - --trigger-http
      - --runtime=java17
      - --allow-unauthenticated